sudo: required
services:
  - docker

before_install:
  - docker build -t 4id3y/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 4id3y/react-test npm test

after_success:
  - docker build -t 4id3y/multi-client ./client
  - docker build -t 4id3y/multi-nginx ./nginx
  - docker build -t 4id3y/multi-server ./server
  - docker build -t 4id3y/multi-worker ./worker
  #Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push images
  - docker push 4id3y/multi-client
  - docker push 4id3y/multi-nginx
  - docker push 4id3y/multi-server
  - docker push 4id3y/multi-worker

